import org.junit.*;
import java.util.*;
import play.test.*;
import models.*;

public class BasicTest extends UnitTest {

    // This tells JUnit to delete the database
    // before each test
    @Before
    public void setup() {
      Fixtures.deleteAll();
    }

    @Test
    public void createAndRetrieveSnippet() {
      // Create a new snippet and save it
      new Snippet("def foo; puts 'hello'; end", "ruby", true).save();

      // Get snippet by id
      // ID autogenerated by Play!
      Snippet foo = Snippet.find("byKeep", true).first();

      // Le test
      assertNotNull(foo);
      assertEquals("ruby", foo.language);
      assertEquals(1, Snippet.count());
    }
}
